import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { generateElementSource } from "../../../packages/core/src/edit/element-templates";
import { NODE_SHAPE_OPTIONS } from "../../../packages/core/src/edit/inspector/presets";
import { renderTikzToSvg } from "../../../packages/core/src/render/index";

type GeneratedNodeShapePreview = Record<string, string | null>;

function main(): Promise<void> {
  return writeGeneratedModule();
}

async function writeGeneratedModule(): Promise<void> {
  const generated: GeneratedNodeShapePreview = {};

  for (const option of NODE_SHAPE_OPTIONS) {
    const snippet = generateElementSource({ kind: "node", shape: option.value, text: "" }, { x: 0, y: 0 });
    const source = ["\\begin{tikzpicture}", `  ${snippet}`, "\\end{tikzpicture}"].join("\n");
    const result = renderTikzToSvg(source, { svg: { padding: 10 } });
    generated[option.value] = namespaceSvgIds(result.svg.svg, `node-shape-${slugify(option.value)}`);
  }

  const moduleSource = [
    "/* eslint-disable */",
    "// This file is auto-generated by apps/web/scripts/generate-node-shape-previews.ts.",
    "// Do not edit it manually.",
    "",
    `export const GENERATED_NODE_SHAPE_PREVIEWS: Record<string, string | null> = ${JSON.stringify(generated, null, 2)};`,
    ""
  ].join("\n");

  const thisDir = dirname(fileURLToPath(import.meta.url));
  const outputPath = resolve(thisDir, "../../../packages/app/src/ui/generated-node-shape-previews.ts");
  const previous = await readIfExists(outputPath);
  if (previous === moduleSource) {
    console.log("[node-shape-previews] up to date");
    return;
  }

  await writeFile(outputPath, moduleSource, "utf8");
  console.log("[node-shape-previews] wrote", outputPath);
}

async function readIfExists(path: string): Promise<string | null> {
  try {
    return await readFile(path, "utf8");
  } catch {
    return null;
  }
}

function slugify(value: string): string {
  return value.trim().toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "") || "shape";
}

function namespaceSvgIds(svg: string, suffix: string): string {
  const idMatches = [...svg.matchAll(/\bid="([^"]+)"/g)];
  if (idMatches.length === 0) {
    return svg;
  }

  const idMap = new Map<string, string>();
  let index = 1;
  for (const match of idMatches) {
    const sourceId = match[1];
    if (!sourceId || idMap.has(sourceId)) {
      continue;
    }
    idMap.set(sourceId, `${sourceId}-${suffix}-${index}`);
    index += 1;
  }

  let result = svg;
  for (const [sourceId, targetId] of idMap) {
    const escapedSourceId = escapeRegExp(sourceId);
    result = result.replace(new RegExp(`\\bid="${escapedSourceId}"`, "g"), `id="${targetId}"`);
    result = result.replace(new RegExp(`url\\(#${escapedSourceId}\\)`, "g"), `url(#${targetId})`);
    result = result.replace(new RegExp(`\\bhref="#${escapedSourceId}"`, "g"), `href="#${targetId}"`);
    result = result.replace(new RegExp(`\\bxlink:href="#${escapedSourceId}"`, "g"), `xlink:href="#${targetId}"`);
  }
  return result;
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

void main().catch((error) => {
  console.error("[node-shape-previews] generation failed:", error);
  process.exitCode = 1;
});