import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { renderTikzToSvgAsync } from "../../src/render/index";
import { OPEN_EXAMPLE_CATALOG } from "../src/ui/examples/open-example-catalog";

type GeneratedOpenExamplePreview = {
  exampleId: string;
  svg: string | null;
  warningCount: number;
  errorCount: number;
  errorMessage: string | null;
};

async function main(): Promise<void> {
  const generated: Record<string, GeneratedOpenExamplePreview> = {};

  for (const example of OPEN_EXAMPLE_CATALOG) {
    try {
      const result = await renderTikzToSvgAsync(example.source, {
        parse: { recover: true },
        svg: { padding: 18 }
      });
      const parseErrors = result.parse.diagnostics.filter((diagnostic) => diagnostic.severity === "error");
      const semanticErrors = result.semantic.diagnostics.filter((diagnostic) => diagnostic.severity === "error");
      const renderErrors = result.renderDiagnostics.filter((diagnostic) => diagnostic.severity === "error");
      const parseWarnings = result.parse.diagnostics.filter((diagnostic) => diagnostic.severity === "warning");
      const semanticWarnings = result.semantic.diagnostics.filter((diagnostic) => diagnostic.severity === "warning");
      const renderWarnings = result.renderDiagnostics.filter((diagnostic) => diagnostic.severity === "warning");

      generated[example.id] = {
        exampleId: example.id,
        svg: result.svg.svg,
        warningCount: parseWarnings.length + semanticWarnings.length + renderWarnings.length,
        errorCount: parseErrors.length + semanticErrors.length + renderErrors.length,
        errorMessage:
          parseErrors[0]?.message ??
          semanticErrors[0]?.message ??
          renderErrors[0]?.message ??
          null
      };
    } catch (error) {
      generated[example.id] = {
        exampleId: example.id,
        svg: null,
        warningCount: 0,
        errorCount: 1,
        errorMessage: error instanceof Error ? error.message : String(error)
      };
    }
  }

  const moduleSource = [
    "/* eslint-disable */",
    "// This file is auto-generated by web/scripts/generate-open-example-previews.ts.",
    "// Do not edit it manually.",
    "",
    "export type GeneratedOpenExamplePreview = {",
    "  exampleId: string;",
    "  svg: string | null;",
    "  warningCount: number;",
    "  errorCount: number;",
    "  errorMessage: string | null;",
    "};",
    "",
    `export const GENERATED_OPEN_EXAMPLE_PREVIEWS: Record<string, GeneratedOpenExamplePreview> = ${JSON.stringify(generated, null, 2)};`,
    ""
  ].join("\n");

  const thisDir = dirname(fileURLToPath(import.meta.url));
  const outputPath = resolve(thisDir, "../src/ui/examples/generated-open-example-previews.ts");
  const previous = await readIfExists(outputPath);
  if (previous === moduleSource) {
    console.log("[open-example-previews] up to date");
    return;
  }

  await writeFile(outputPath, moduleSource, "utf8");
  console.log("[open-example-previews] wrote", outputPath);
}

async function readIfExists(path: string): Promise<string | null> {
  try {
    return await readFile(path, "utf8");
  } catch {
    return null;
  }
}

void main().catch((error) => {
  console.error("[open-example-previews] generation failed:", error);
  process.exitCode = 1;
});
