export const FEATURE_IDS = [
  "path_statement",
  "scope_statement",
  "foreach_statement",
  "foreach_path_operation",
  "foreach_node_operation",
  "unknown_statement",
  "options_structured",
  "path_shading",
  "path_shadows",
  "arrow_tips",
  "path_operators_basic",
  "path_operator_curves",
  "path_cycle",
  "shape_rectangle",
  "shape_circle",
  "shape_diamond",
  "shape_trapezium",
  "matrix_node",
  "named_coordinates",
  "to_operation",
  "svg_operation",
  "let_operation",
  "keyword_ellipse",
  "keyword_arc",
  "keyword_grid",
  "keyword_to",
  "keyword_controls",
  "keyword_and",
  "svg_path",
  "svg_circle",
  "svg_text",
  "render_pipeline"
] as const;

export type FeatureId = (typeof FEATURE_IDS)[number];
