import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const outputPath = path.resolve(fileURLToPath(new URL("../src/generated/build-info.ts", import.meta.url)));
const buildDate = new Date().toISOString().slice(0, 10);

mkdirSync(path.dirname(outputPath), { recursive: true });
writeFileSync(outputPath, `/* auto-generated by apps/landing/scripts/generate-build-info.mts */\n\nexport const landingBuildDate = ${JSON.stringify(buildDate)};\n`);
console.log(`[landing-build-info] wrote ${outputPath} with build date ${buildDate}`);
