import type { ArrowTipKind } from "../types.js";
import { parseLength } from "../coords/parse-length.js";

export const NAMED_COLORS = new Set([
  "black",
  "darkgray",
  "white",
  "gray",
  "lightgray",
  "red",
  "green",
  "blue",
  "cyan",
  "magenta",
  "yellow",
  "lime",
  "olive",
  "orange",
  "pink",
  "violet",
  "purple",
  "teal",
  "brown",
]);

export const COLOR_HEX: Record<string, string> = {
  black: "#000000",
  darkgray: "#404040",
  white: "#ffffff",
  gray: "#808080",
  lightgray: "#bfbfbf",
  red: "#ff0000",
  green: "#00ff00",
  blue: "#0000ff",
  cyan: "#00ffff",
  magenta: "#ff00ff",
  yellow: "#ffff00",
  lime: "#bfff00",
  olive: "#808000",
  orange: "#ff8000",
  pink: "#ffbfbf",
  violet: "#800080",
  purple: "#bf0040",
  teal: "#008080",
  brown: "#bf8040"
};

export const NON_STYLE_OPTION_KEYS = new Set([
  "start angle",
  "end angle",
  "delta angle",
  "step",
  "xstep",
  "ystep",
  "x step",
  "y step",
  "name",
  "alias",
  "node contents",
  "at",
  "shape",
  "anchor",
  "inner sep",
  "inner xsep",
  "inner ysep",
  "outer sep",
  "outer xsep",
  "outer ysep",
  "minimum width",
  "minimum height",
  "minimum size",
  "aspect",
  "shape aspect",
  "shape border rotate",
  "shape border uses incircle",
  "trapezium left angle",
  "trapezium right angle",
  "trapezium angle",
  "trapezium stretches",
  "trapezium stretches body",
  "isosceles triangle apex angle",
  "isosceles triangle stretches",
  "kite upper vertex angle",
  "kite lower vertex angle",
  "kite vertex angles",
  "dart tip angle",
  "dart tail angle",
  "circular sector angle",
  "cylinder uses custom fill",
  "cylinder end fill",
  "cylinder body fill",
  "cloud puffs",
  "cloud puff arc",
  "cloud ignores aspect",
  "starburst points",
  "starburst point height",
  "random starburst",
  "signal pointer angle",
  "signal to",
  "signal from",
  "tape bend",
  "tape bend top",
  "tape bend bottom",
  "tape bend height",
  "callout relative pointer",
  "callout absolute pointer",
  "callout pointer shorten",
  "callout pointer width",
  "callout pointer arc",
  "callout pointer start size",
  "callout pointer end size",
  "callout pointer segments",
  "single arrow tip angle",
  "single arrow head extend",
  "single arrow head indent",
  "double arrow tip angle",
  "double arrow head extend",
  "double arrow head indent",
  "regular polygon sides",
  "regular polygon rotate",
  "star points",
  "star point ratio",
  "star point height",
  "star rotate",
  "auto",
  "pos",
  "node distance",
  "on grid",
  "above",
  "below",
  "left",
  "right",
  "above left",
  "above right",
  "below left",
  "below right",
  "above of",
  "below of",
  "left of",
  "right of",
  "above left of",
  "above right of",
  "below left of",
  "below right of",
  "base left",
  "base right",
  "mid left",
  "mid right",
  "node font",
  "font",
  "text width",
  "text height",
  "text depth",
  "node halign header",
  "badness warnings for centered text",
  "execute at begin node",
  "execute at end node",
  "name prefix",
  "name suffix",
  "name path",
  "name path global",
  "name path local",
  "name intersections",
  "every node/.style",
  "every node/.append style",
  "every rectangle node/.style",
  "every rectangle node/.append style",
  "every circle node/.style",
  "every circle node/.append style",
  "every diamond node/.style",
  "every diamond node/.append style",
  "every trapezium node/.style",
  "every trapezium node/.append style",
  "every isosceles triangle node/.style",
  "every isosceles triangle node/.append style",
  "every kite node/.style",
  "every kite node/.append style",
  "every dart node/.style",
  "every dart node/.append style",
  "every circular sector node/.style",
  "every circular sector node/.append style",
  "every cylinder node/.style",
  "every cylinder node/.append style",
  "every cloud node/.style",
  "every cloud node/.append style",
  "every starburst node/.style",
  "every starburst node/.append style",
  "every signal node/.style",
  "every signal node/.append style",
  "every tape node/.style",
  "every tape node/.append style",
  "every rectangle callout node/.style",
  "every rectangle callout node/.append style",
  "every ellipse callout node/.style",
  "every ellipse callout node/.append style",
  "every cloud callout node/.style",
  "every cloud callout node/.append style",
  "every single arrow node/.style",
  "every single arrow node/.append style",
  "every double arrow node/.style",
  "every double arrow node/.append style",
  "transform shape"
]);

export const NON_STYLE_OPTION_FLAGS = new Set([
  "behind path",
  "in front of path",
  "circle",
  "ellipse",
  "rectangle",
  "diamond",
  "trapezium",
  "semicircle",
  "regular polygon",
  "star",
  "isosceles triangle",
  "kite",
  "dart",
  "circular sector",
  "cylinder",
  "cloud",
  "starburst",
  "signal",
  "tape",
  "rectangle callout",
  "ellipse callout",
  "cloud callout",
  "single arrow",
  "double arrow",
  "cloud ignores aspect",
  "random starburst",
  "isosceles triangle stretches",
  "trapezium stretches",
  "trapezium stretches body",
  "coordinate",
  "above",
  "below",
  "left",
  "right",
  "above left",
  "above right",
  "below left",
  "below right",
  "on grid",
  "above of",
  "below of",
  "left of",
  "right of",
  "above left of",
  "above right of",
  "below left of",
  "below right of",
  "base left",
  "base right",
  "mid left",
  "mid right",
  "centered",
  "midway",
  "near start",
  "near end",
  "very near start",
  "very near end",
  "at start",
  "at end",
  "swap",
  "sloped",
  "allow upside down",
  "bend at start",
  "bend at end",
  "transform shape",
  "dash expand off",
  "dash expand on"
]);

export const PT_PER_CM = parseLength("1cm", "cm") ?? 28.4527559055;
export const DEFAULT_TEXT_FONT_SIZE = 9.96264;
export const FONT_SIZE_COMMAND_FACTORS: Record<string, number> = {
  "\\tiny": 0.5,
  "\\scriptsize": 0.7,
  "\\footnotesize": 0.8,
  "\\small": 0.9,
  "\\normalsize": 1,
  "\\large": 1.2,
  "\\Large": 1.44,
  "\\LARGE": 1.728,
  "\\huge": 2.074,
  "\\Huge": 2.488,
  "\\pgfutil@font@tiny": 0.5,
  "\\pgfutil@font@scriptsize": 0.7,
  "\\pgfutil@font@footnotesize": 0.8,
  "\\pgfutil@font@small": 0.9,
  "\\pgfutil@font@normalsize": 1,
  "\\pgfutil@font@large": 1.2,
  "\\pgfutil@font@Large": 1.44,
  "\\pgfutil@font@LARGE": 1.728,
  "\\pgfutil@font@huge": 2.074,
  "\\pgfutil@font@Huge": 2.488
};
export const DEFAULT_DOUBLE_DISTANCE = 0.6;
export const DEFAULT_ARROW_LENGTH = 8;
export const DEFAULT_ARROW_WIDTH = 6;
export const DEFAULT_AXIS_TOP_COLOR = COLOR_HEX.gray;
export const DEFAULT_AXIS_MIDDLE_COLOR = "#c0c0c0";
export const DEFAULT_AXIS_BOTTOM_COLOR = COLOR_HEX.white;
export const DEFAULT_BALL_COLOR = COLOR_HEX.blue;
export const DEFAULT_RADIAL_INNER_COLOR = COLOR_HEX.gray;
export const DEFAULT_RADIAL_OUTER_COLOR = COLOR_HEX.white;

export const ARROW_NAME_ALIASES = ([
  { name: "computer modern rightarrow", kind: "cm-rightarrow" },
  { name: "classical tikz rightarrow", kind: "to" },
  { name: "straight barb", kind: "straight-barb" },
  { name: "arc barb", kind: "arc-barb" },
  { name: "tee barb", kind: "tee-barb" },
  { name: "round cap", kind: "round-cap" },
  { name: "butt cap", kind: "butt-cap" },
  { name: "triangle cap", kind: "triangle-cap" },
  { name: "fast triangle", kind: "triangle-cap" },
  { name: "fast round", kind: "round-cap" },
  { name: "turned square", kind: "kite" },
  { name: "rightarrow", kind: "cm-rightarrow" },
  { name: "parenthesis", kind: "arc-barb" },
  { name: "bracket", kind: "tee-barb" },
  { name: "rectangle", kind: "square" },
  { name: "ellipse", kind: "circle" },
  { name: "diamond", kind: "kite" },
  { name: "kite", kind: "kite" },
  { name: "square", kind: "square" },
  { name: "circle", kind: "circle" },
  { name: "rays", kind: "rays" },
  { name: "latex", kind: "latex" },
  { name: "implies", kind: "implies" },
  { name: "stealth", kind: "stealth" },
  { name: "triangle", kind: "triangle" },
  { name: "hooks", kind: "hooks" },
  { name: "bar", kind: "bar" },
  { name: "to", kind: "to" }
] as Array<{ name: string; kind: ArrowTipKind }>).sort((left, right) => right.name.length - left.name.length);
