import type { ArrowTipKind } from "../types.js";
import { parseLength } from "../coords/parse-length.js";

export const NAMED_COLORS = new Set([
  "black",
  "white",
  "red",
  "blue",
  "green",
  "yellow",
  "orange",
  "brown",
  "gray",
  "purple",
  "cyan",
  "magenta"
]);

export const COLOR_HEX: Record<string, string> = {
  black: "#000000",
  white: "#ffffff",
  red: "#ff0000",
  blue: "#0000ff",
  green: "#008000",
  yellow: "#ffff00",
  orange: "#ffa500",
  brown: "#8b4513",
  gray: "#808080",
  purple: "#800080",
  cyan: "#00ffff",
  magenta: "#ff00ff"
};

export const NON_STYLE_OPTION_KEYS = new Set([
  "start angle",
  "end angle",
  "delta angle",
  "step",
  "xstep",
  "ystep",
  "x step",
  "y step",
  "name",
  "alias",
  "node contents",
  "at",
  "shape",
  "anchor",
  "inner sep",
  "inner xsep",
  "inner ysep",
  "outer sep",
  "outer xsep",
  "outer ysep",
  "minimum width",
  "minimum height",
  "minimum size",
  "shape aspect",
  "shape border rotate",
  "shape border uses incircle",
  "auto",
  "pos",
  "node distance",
  "on grid",
  "above",
  "below",
  "left",
  "right",
  "above left",
  "above right",
  "below left",
  "below right",
  "above of",
  "below of",
  "left of",
  "right of",
  "above left of",
  "above right of",
  "below left of",
  "below right of",
  "base left",
  "base right",
  "mid left",
  "mid right",
  "node font",
  "font",
  "text width",
  "text height",
  "text depth",
  "node halign header",
  "badness warnings for centered text",
  "execute at begin node",
  "execute at end node",
  "name prefix",
  "name suffix",
  "every node/.style",
  "every node/.append style",
  "every rectangle node/.style",
  "every rectangle node/.append style",
  "every circle node/.style",
  "every circle node/.append style",
  "transform shape"
]);

export const NON_STYLE_OPTION_FLAGS = new Set([
  "behind path",
  "in front of path",
  "circle",
  "ellipse",
  "rectangle",
  "coordinate",
  "above",
  "below",
  "left",
  "right",
  "above left",
  "above right",
  "below left",
  "below right",
  "on grid",
  "above of",
  "below of",
  "left of",
  "right of",
  "above left of",
  "above right of",
  "below left of",
  "below right of",
  "base left",
  "base right",
  "mid left",
  "mid right",
  "centered",
  "midway",
  "near start",
  "near end",
  "very near start",
  "very near end",
  "at start",
  "at end",
  "swap",
  "sloped",
  "allow upside down",
  "bend at start",
  "bend at end",
  "transform shape",
  "dash expand off",
  "dash expand on"
]);

export const PT_PER_CM = parseLength("1cm", "cm") ?? 28.4527559055;
export const DEFAULT_TEXT_FONT_SIZE = 9.96264;
export const FONT_SIZE_COMMAND_FACTORS: Record<string, number> = {
  "\\tiny": 0.5,
  "\\scriptsize": 0.7,
  "\\footnotesize": 0.8,
  "\\small": 0.9,
  "\\normalsize": 1,
  "\\large": 1.2,
  "\\Large": 1.44,
  "\\LARGE": 1.728,
  "\\huge": 2.074,
  "\\Huge": 2.488,
  "\\pgfutil@font@tiny": 0.5,
  "\\pgfutil@font@scriptsize": 0.7,
  "\\pgfutil@font@footnotesize": 0.8,
  "\\pgfutil@font@small": 0.9,
  "\\pgfutil@font@normalsize": 1,
  "\\pgfutil@font@large": 1.2,
  "\\pgfutil@font@Large": 1.44,
  "\\pgfutil@font@LARGE": 1.728,
  "\\pgfutil@font@huge": 2.074,
  "\\pgfutil@font@Huge": 2.488
};
export const DEFAULT_DOUBLE_DISTANCE = 0.6;
export const DEFAULT_ARROW_LENGTH = 8;
export const DEFAULT_ARROW_WIDTH = 6;
export const DEFAULT_AXIS_TOP_COLOR = COLOR_HEX.gray;
export const DEFAULT_AXIS_MIDDLE_COLOR = "#c0c0c0";
export const DEFAULT_AXIS_BOTTOM_COLOR = COLOR_HEX.white;
export const DEFAULT_BALL_COLOR = COLOR_HEX.blue;
export const DEFAULT_RADIAL_INNER_COLOR = COLOR_HEX.gray;
export const DEFAULT_RADIAL_OUTER_COLOR = COLOR_HEX.white;

export const ARROW_NAME_ALIASES = ([
  { name: "computer modern rightarrow", kind: "cm-rightarrow" },
  { name: "classical tikz rightarrow", kind: "to" },
  { name: "rightarrow", kind: "cm-rightarrow" },
  { name: "straight barb", kind: "bar" },
  { name: "tee barb", kind: "bar" },
  { name: "arc barb", kind: "hooks" },
  { name: "triangle cap", kind: "triangle" },
  { name: "fast triangle", kind: "triangle" },
  { name: "round cap", kind: "bar" },
  { name: "bracket", kind: "bar" },
  { name: "implies", kind: "implies" },
  { name: "stealth", kind: "stealth" },
  { name: "latex", kind: "latex" },
  { name: "triangle", kind: "triangle" },
  { name: "hooks", kind: "hooks" },
  { name: "bar", kind: "bar" },
  { name: "to", kind: "to" }
] as Array<{ name: string; kind: ArrowTipKind }>).sort((left, right) => right.name.length - left.name.length);
