export { FeatureFlags } from "./ast/features.js";
export { parseTikz } from "./parser/index.js";
export { applyEdit } from "./edit/apply.js";
export { collectTikzSnippetsFromDocs, extractTikzSnippetsFromSource } from "./corpus/extract.js";
export { evaluateTikzFigure } from "./semantic/index.js";
export { emitSvg } from "./svg/index.js";
export { renderTikzToSvg } from "./render/index.js";
export { capabilityMatrix, FEATURE_IDS } from "./capabilities/index.js";

export type { ParseTikzOptions, ParseTikzResult } from "./parser/index.js";
export type { TikzEdit, ApplyEditResult } from "./edit/types.js";
export type { TikzSnippet, TikzSnippetKind } from "./corpus/extract.js";
export type { EvaluateTikzResult } from "./semantic/index.js";
export type { EmitSvgResult, EmitSvgOptions, SvgViewBox } from "./svg/index.js";
export type { RenderTikzOptions, RenderTikzToSvgResult } from "./render/index.js";
export type { CapabilityMatrix, CapabilityRow, LayerStatus, FeatureId } from "./capabilities/index.js";
export type * from "./ast/types.js";
export type * from "./diagnostics/types.js";
export type * from "./semantic/index.js";
export type * from "./options/types.js";
